version: '3'

services:
  web:
    build:   #current working directory, 
             #current build context but right now the docker file is named as Dockerfil.dev
      context: . #context option is essentially specifying where we want all the files and folders for this image to be pulled from. I this case we want the context to be in
                 #the current workding directory that's why dot is being added.
      dockerfile: Dockerfile.dev #location of the dockerfile to be used to construct the image for the web service.
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_mo ndules #meaning: do not try to map a folder up against /app/node_modules inside the container
      - .:/app # its saying get the pwd/path and take that folder and everything inside of it and map it to the /app folder running inside of our container
  
  tests: #RUUNING LIVE TEST (another container that its job is to running the tests,re running anytime the files inside of our volume is changed.)
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules #setup-place holder and make we dont' accidentally override that directory
      - .:/app

      #next step, is we need to override the default command when the test service is created
    command: ["npm","run","test"]


      